[build]
builder = "nixpacks"

[deploy]
startCommand = "uvicorn goldenverba.server.api:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"

# PostgreSQL configuration will be auto-injected by Railway PostgreSQL service
# DATABASE_URL will be provided by Railway PostgreSQL service