name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        working-directory: ./frontend
        run: bun install

      - name: Run Tests
        working-directory: ./frontend
        run: bun test

  backend-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python
        run: uv python install 3.11

      - name: Install Dependencies
        run: uv sync --group dev --group test

      - name: Run Linting
        run: uv run ruff check goldenverba

      - name: Run Formatting Check
        run: uv run ruff format --check goldenverba

      - name: Run Type Checking
        run: uv run ty check goldenverba

      - name: Run Tests
        run: uv run pytest --cov=goldenverba --cov-report=xml

  build:
    needs: [frontend-test, backend-test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        working-directory: ./frontend
        run: npm install --legacy-peer-deps

      - name: Build
        working-directory: ./frontend
        run: npm run build
